<?php
declare(strict_types=1);

namespace SamIT\Yii2\VirtualFields;


use yii\db\Expression;
use yii\db\ExpressionInterface;

class VirtualFieldExpression extends Expression
{
    public function __toString()
    {
        throw new \Exception('noo');
        return parent::__toString(); // TODO: Change the autogenerated stub
    }


}